
name: "обучение"
map: "[(*][1+][+_][4+][*+][5+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][2+][*+][3+][+_][6+][)*][*+] "
types:
    - green: 5
    - blue: 4
    - green: 2
    - red: 1