
name: "обучение"
map: "[(*][1+][+_][4+][*+][5+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][2+][*+][3+][+_][6+][)*][*+] "
types:
    - green:
        count: 2
        hp: 5
    - red:
        count: 1
        hp: 20
    - green:
        count: 2
        hp: 10