
name: "обучение"
enemy count: 10
map: "[(*][1+][+_][4+][*+][5+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][*+][+_][*+][+_][*+][+_][*+]
[+_][2+][*+][3+][+_][6+][)*][*+] "
